#ifndef RECOGNITIONCORE_GLOBAL_H
#define RECOGNITIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECOGNITIONCORE_LIBRARY)
#  define RECOGNITIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define RECOGNITIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RECOGNITIONCORE_GLOBAL_H
